### ISSUE TITLE
Change font size in do_PathwayActivityPlot

### ISSUE THREAD

**Issue by france-hub** [enblacar/SCpubr#25] opened 2023-03-23 18:50 UTC
Hello!

Thanks for this package! 
I am trying to increase the font size of this heatmap
![HeatPath](https://user-images.githubusercontent.com/56587709/227317584-919c1ce0-1111-4989-b4a5-0113ebf9dfa6.png)

This is the code to get the heatmap:

```
Use SCpubr and decoupleR for pathway activity inference
# Retrieve prior knowledge network.
network <- decoupleR::get_progeny(organism = "human")

# Run weighted means algorithm.
activities <- decoupleR::run_wmean(mat = as.matrix(CD8@assays[["RNA"]]@data),
                                   network = network,
                                   .source = "source",
                                   .targe = "target",
                                   .mor = "weight",
                                   times = 100,
                                   minsize = 5)

# General heatmap.
out <- SCpubr::do_PathwayActivityPlot(sample = CD8,
                                      activities = activities,
                                      split.by = "group_id", cluster_rows = FALSE)
p.patHeat <- out$heatmaps$average_scores
```
Using the font.size argument (I have tried font.size 10,20,40) does not work. 

Can you help?

Thanks
Francesco

**Comment by enblacar** [comment] 2023-03-23 23:24
Hi @france-hub,

Thanks for using my package!

Indeed, this is a bug that I had fixed in the development version of the package shortly after update `v1.2.0` rolled out. However, due to my decision to work on an update `v2.0.0`, where I am replacing all `ComplexHeatmap` plots with` ggplot2` counterparts, I cannot simply tell you to download the last commit and try again.

To give you a quick hotfix though, I have modified the functions present in `SCpubr v1.2.0` and fixed this bug. After testing it, it works as intended. For this, you will have to copy-paste the following code (I also modified the `do_TFActivityPlot()` function) in your current R session.

This will define the functions in your local environment and you should then run the code using those instead of the `SCpubr::` variants.

**do_PathwayActivityPlot()**
```r
do_PathwayActivityPlot <- function(sample,
                                   activities,
                                   group.by = NULL,
                                   split.by = NULL,
                                   plot_FeaturePlots = FALSE,
                                   plot_Heatmaps = TRUE,
                                   plot_GeyserPlots = FALSE,
                                   row_title = NULL,
                                   column_title = NULL,
                                   flip = FALSE,
                                   cluster_cols = TRUE,
                                   cluster_rows = TRUE,
                                   row_names_rot = 0,
                                   column_names_rot = 45,
                                   cell_size = 8,
                                   pt.size = 1,
                                   plot_cell_borders = TRUE,
                                   border.size = 2,
                                   na.value = "grey75",
                                   legend.position = "bottom",
                                   heatmap.legend.length = 75,
                                   heatmap.legend.width = 5,
                                   heatmap.legend.framecolor = "black",
                                   legend.width = 1,
                                   legend.length = 20,
                                   legend.framewidth = 0.5,
                                   legend.tickwidth = 0.5,
                                   legend.framecolor = "grey50",
                                   legend.tickcolor = "white",
                                   legend.type = "colorbar",
                                   font.size = 14,
                                   font.type = "sans",
                                   rotate_x_axis_labels = 45,
                                   enforce_symmetry = TRUE,
                                   geyser_order_by_mean = TRUE,
                                   geyser_scale_type = "continuous",
                                   viridis_color_map = "G",
                                   viridis_direction = 1,
                                   min.cutoff = NULL,
                                   max.cutoff = NULL){
  
  SCpubr:::check_suggests(function_name = "do_PathwayActivityPlot")
  # Check if the sample provided is a Seurat object.
  SCpubr:::check_Seurat(sample = sample)
  
  # Check logical parameters.
  logical_list <- list("plot_FeaturePlots" = plot_FeaturePlots,
                       "plot_Heatmaps" = plot_Heatmaps,
                       "plot_GeyserPlots" = plot_GeyserPlots,
                       "flip" = flip,
                       "cluster_cols" = cluster_cols,
                       "cluster_rows" = cluster_rows,
                       "plot_cell_borders" = plot_cell_borders,
                       "geyser_order_by_mean" = geyser_order_by_mean,
                       "enforce_symmetry" = enforce_symmetry)
  SCpubr:::check_type(parameters = logical_list, required_type = "logical", test_function = is.logical)
  # Check numeric parameters.
  numeric_list <- list("row_names_rot" = row_names_rot,
                       "column_names_rot" = column_names_rot,
                       "cell_size" = cell_size,
                       "heatmap.legend.length" = heatmap.legend.length,
                       "heatmap.legend.width" = heatmap.legend.width,
                       "pt.size" = pt.size,
                       "border.size" = border.size,
                       "font.size" = font.size,
                       "legend.width" = legend.width,
                       "legend.length" = legend.length,
                       "legend.framewidth" = legend.framewidth,
                       "legend.tickwidth" = legend.tickwidth,
                       "viridis_direction" = viridis_direction,
                       "rotate_x_axis_labels" = rotate_x_axis_labels,
                       "min.cutoff" = min.cutoff,
                       "max.cutoff" = max.cutoff)
  SCpubr:::check_type(parameters = numeric_list, required_type = "numeric", test_function = is.numeric)
  # Check character parameters.
  character_list <- list("group.by" = group.by,
                         "split.by" = split.by,
                         "na.value" = na.value,
                         "legend.position" = legend.position,
                         "legend.framecolor" = legend.framecolor,
                         "font.type" = font.type,
                         "legend.tickcolor" = legend.tickcolor,
                         "legend.type" = legend.type,
                         "geyser_scale_type" = geyser_scale_type,
                         "viridis_color_map" = viridis_color_map)
  SCpubr:::check_type(parameters = character_list, required_type = "character", test_function = is.character)
  
  SCpubr:::check_colors(legend.framecolor, parameter_name = "legend.framecolor")
  SCpubr:::check_colors(legend.tickcolor, parameter_name = "legend.tickcolor")
  SCpubr:::check_colors(heatmap.legend.framecolor, parameter_name = "heatmap.legend.framecolor")
  SCpubr:::check_colors(na.value, parameter_name = "na.value")
  
  SCpubr:::check_parameters(parameter = font.type, parameter_name = "font.type")
  SCpubr:::check_parameters(parameter = legend.type, parameter_name = "legend.type")
  SCpubr:::check_parameters(parameter = legend.position, parameter_name = "legend.position")
  SCpubr:::check_parameters(parameter = viridis_direction, parameter_name = "viridis_direction")
  SCpubr:::check_parameters(parameter = viridis_color_map, parameter_name = "viridis_color_map")
  SCpubr:::check_parameters(parameter = rotate_x_axis_labels, parameter_name = "rotate_x_axis_labels")
  
  
  `%v%` <- ComplexHeatmap::`%v%`
  `%>%` <- magrittr::`%>%`
  
  sample[["progeny"]] <- activities %>%
    dplyr::filter(.data$statistic == "norm_wmean") %>%
    tidyr::pivot_wider(id_cols = "source",
                       names_from = "condition",
                       values_from = "score") %>%
    tibble::column_to_rownames("source") %>%
    Seurat::CreateAssayObject()
  
  Seurat::DefaultAssay(sample) <- "progeny"
  # Scale data.
  sample <- Seurat::ScaleData(object = sample, verbose = FALSE)
  
  list.out <- list()
  
  if (isTRUE(plot_FeaturePlots)){
    list.features <- list()
    for (pathway in sort(rownames(sample))){
      p <- do_FeaturePlot(sample = sample,
                          features = pathway,
                          assay = "progeny",
                          reduction = "umap",
                          slot = "scale.data",
                          pt.size = pt.size,
                          order = FALSE,
                          border.size = border.size,
                          enforce_symmetry = enforce_symmetry,
                          plot_cell_borders = plot_cell_borders,
                          font.size = font.size,
                          font.type = font.type,
                          legend.title = paste0(pathway, " activity"),
                          legend.position = legend.position,
                          legend.type = legend.type,
                          legend.framecolor = legend.framecolor,
                          legend.tickcolor = legend.tickcolor,
                          legend.framewidth = legend.framewidth,
                          legend.tickwidth = legend.tickwidth,
                          legend.length = legend.length,
                          legend.width = legend.width,
                          viridis_color_map = viridis_color_map,
                          viridis_direction = viridis_direction,
                          min.cutoff = if (is.null(min.cutoff)) {NA} else {min.cutoff},
                          max.cutoff = if (is.null(max.cutoff)) {NA} else {max.cutoff})
      
      list.features[[pathway]] <- p
    }
    list.out[["feature_plots"]] <- list.features
  }
  
  if (isTRUE(plot_GeyserPlots)){
    list.geysers <- list()
    for (pathway in sort(rownames(sample))){
      p <- do_GeyserPlot(sample = sample,
                         assay = "progeny",
                         slot = "scale.data",
                         features = pathway,
                         group.by = group.by,
                         pt.size = pt.size,
                         border.size = border.size,
                         enforce_symmetry = enforce_symmetry,
                         scale_type = geyser_scale_type,
                         order_by_mean = geyser_order_by_mean,
                         plot_cell_borders = plot_cell_borders,
                         font.size = font.size,
                         font.type = font.type,
                         legend.position = legend.position,
                         legend.type = legend.type,
                         legend.framecolor = legend.framecolor,
                         legend.tickcolor = legend.tickcolor,
                         legend.framewidth = legend.framewidth,
                         legend.tickwidth = legend.tickwidth,
                         legend.length = legend.length,
                         legend.width = legend.width,
                         xlab = if (is.null(group.by)) {"Clusters"} else {group.by},
                         ylab = paste0(pathway, " activity"),
                         legend.title = paste0(pathway, " activity"),
                         rotate_x_axis_labels = rotate_x_axis_labels,
                         viridis_color_map = viridis_color_map,
                         viridis_direction = viridis_direction,
                         min.cutoff = min.cutoff,
                         max.cutoff = max.cutoff)
      list.geysers[[pathway]] <- p
    }
    list.out[["geyser_plots"]] <- list.geysers
  }
  
  
  if (isTRUE(plot_Heatmaps)){
    # Start the process.
    if (is.null(group.by)){
      sample@meta.data[, "dummy"] <- sample@active.ident
    } else {
      sample@meta.data[, "dummy"] <- sample@meta.data[, group.by]
    }
    
    group.by <- "dummy"
    if (is.null(split.by)){
      suppressMessages({
        data <- sample@assays$progeny@scale.data %>%
          t() %>%
          as.data.frame() %>%
          tibble::rownames_to_column(var = "cell") %>%
          dplyr::left_join(y = {sample@meta.data[, group.by, drop = FALSE] %>%
              tibble::rownames_to_column(var = "cell")},
              by = "cell") %>%
          dplyr::select(-dplyr::all_of(c("cell"))) %>%
          tidyr::pivot_longer(cols = -dplyr::all_of(c(group.by)),
                              names_to = "source",
                              values_to = "score") %>%
          dplyr::group_by(.data[[group.by]], .data$source) %>%
          dplyr::summarise(mean = mean(.data$score)) %>%
          tidyr::pivot_wider(id_cols = dplyr::all_of(c(group.by)),
                             names_from = 'source',
                             values_from = 'mean') %>%
          tibble::column_to_rownames(group.by) %>%
          as.matrix()
      })
      
      row_title <- {
        if (!(is.null(row_title))){
          row_title
        } else {
          ""
        }}
      
      column_title <- {
        if (!(is.null(column_title))){
          column_title
        } else {
          ""
        }}
      
      if (isTRUE(flip)){
        data <- t(data)
      }
      
      range.data <- c(min(data), max(data))
      if (!is.null(min.cutoff) & !is.null(max.cutoff)){
        assertthat::assert_that(min.cutoff < max.cutoff,
                                msg = paste0("The value provided for min.cutoff (", min.cutoff, ") has to be lower than the value provided to max.cutoff (", max.cutoff, "). Please select another value."))
      }
      
      if (!is.null(min.cutoff)){
        assertthat::assert_that(min.cutoff >= range.data[1],
                                msg = paste0("The value provided for min.cutoff (", min.cutoff, ") is lower than the minimum value in the enrichment matrix (", range.data[1], "). Please select another value."))
        range.data <- c(min.cutoff, range.data[2])
      }
      
      if (!is.null(max.cutoff)){
        assertthat::assert_that(max.cutoff <= range.data[2],
                                msg = paste0("The value provided for max.cutoff (", max.cutoff, ") is lower than the maximum value in the enrichment matrix (", range.data[2], "). Please select another value."))
        range.data <- c(range.data[1], max.cutoff)
      }
      
      out <- SCpubr:::heatmap_inner(data,
                           legend.title = "Pathway activity",
                           column_title = column_title,
                           row_title = row_title,
                           cluster_columns = cluster_cols,
                           cluster_rows = cluster_rows,
                           column_names_rot = column_names_rot,
                           row_names_rot = row_names_rot,
                           cell_size = cell_size,
                           na.value = na.value,
                           data_range = "both",
                           range.data = range.data,
                           legend.position = legend.position,
                           legend.length = heatmap.legend.length,
                           legend.width = heatmap.legend.width,
                           legend.framecolor = heatmap.legend.framecolor,
                           symmetrical_scale = enforce_symmetry,
                           use_viridis = if (isFALSE(enforce_symmetry)) {TRUE} else {FALSE},
                           viridis_color_map = viridis_color_map,
                           viridis_direction = viridis_direction,
                           fontsize = font.size)
      h <- out[["heatmap"]]
      h_legend <- out[["legend"]]
      ComplexHeatmap::ht_opt("HEATMAP_LEGEND_PADDING" = ggplot2::unit(8, "mm"))
      suppressWarnings({
        grDevices::pdf(NULL)
        h <- ComplexHeatmap::draw(h,
                                  heatmap_legend_list = h_legend,
                                  heatmap_legend_side = if (legend.position %in% c("top", "bottom")){"bottom"} else {"right"},
                                  padding = ggplot2::unit(c(5, 5, 5, 5), "mm"))
        grDevices::dev.off()
      })
    } else {
      split.values <- as.character(sort(unique(sample@meta.data %>% dplyr::pull(!!rlang::sym(split.by)))))
      list.heatmaps <- list()
      # Get the maximum range.
      data <- sample@assays$progeny@scale.data %>%
        t() %>%
        as.data.frame() %>%
        tibble::rownames_to_column(var = "cell") %>%
        dplyr::left_join(y = {sample@meta.data[, c(group.by, split.by)] %>%
            tibble::rownames_to_column(var = "cell")},
            by = "cell") %>%
        dplyr::select(-dplyr::all_of(c("cell", split.by))) %>%
        tidyr::pivot_longer(cols = -dplyr::all_of(c(group.by)),
                            names_to = "source",
                            values_to = "score") %>%
        dplyr::group_by(.data[[group.by]], .data$source) %>%
        dplyr::summarise(mean = mean(.data$score)) %>%
        tidyr::pivot_wider(id_cols = dplyr::all_of(c(group.by)),
                           names_from = 'source',
                           values_from = 'mean') %>%
        tibble::column_to_rownames(group.by) %>%
        as.matrix()
      range.data <- c(min(data), max(data))
      
      if (!is.null(min.cutoff)){
        assertthat::assert_that(min.cutoff >= range.data[1],
                                msg = paste0("The value provided for min.cutoff (", min.cutoff, ") is lower than the minimum value in the enrichment matrix (", range.data[1], "). Please select another value."))
        range.data <- c(min.cutoff, range.data[2])
      }
      
      if (!is.null(max.cutoff)){
        assertthat::assert_that(max.cutoff <= range.data[2],
                                msg = paste0("The value provided for max.cutoff (", max.cutoff, ") is lower than the maximum value in the enrichment matrix (", range.data[2], "). Please select another value."))
        range.data <- c(range.data[1], max.cutoff)
        
      }
      for (split.value in split.values){
        suppressMessages({
          data <- sample@assays$progeny@scale.data %>%
            t() %>%
            as.data.frame() %>%
            tibble::rownames_to_column(var = "cell") %>%
            dplyr::left_join(y = {sample@meta.data[, c(group.by, split.by)] %>%
                tibble::rownames_to_column(var = "cell")},
                by = "cell") %>%
            dplyr::filter(.data[[split.by]] == split.value) %>%  # This is key.
            dplyr::select(-dplyr::all_of(c("cell", split.by))) %>%
            tidyr::pivot_longer(cols = -dplyr::all_of(c(group.by)),
                                names_to = "source",
                                values_to = "score") %>%
            dplyr::group_by(.data[[group.by]], .data$source) %>%
            dplyr::summarise(mean = mean(.data$score)) %>%
            tidyr::pivot_wider(id_cols = dplyr::all_of(c(group.by)),
                               names_from = 'source',
                               values_from = 'mean') %>%
            tibble::column_to_rownames(group.by) %>%
            as.matrix()
        })
        
        row_title <- split.value
        column_title <- ""
        
        if (isTRUE(flip)){
          data <- t(data)
        }
        
        
        out <- SCpubr:::heatmap_inner(data,
                             legend.title = "Pathway activity",
                             column_title = column_title,
                             row_title = row_title,
                             cluster_columns = cluster_cols,
                             cluster_rows = cluster_rows,
                             range.data = range.data,
                             column_names_rot = column_names_rot,
                             row_names_rot = row_names_rot,
                             cell_size = cell_size,
                             na.value = na.value,
                             legend.position = legend.position,
                             legend.length = heatmap.legend.length,
                             legend.width = heatmap.legend.width,
                             legend.framecolor = heatmap.legend.framecolor,
                             symmetrical_scale = enforce_symmetry,
                             use_viridis = if (isFALSE(enforce_symmetry)) {TRUE} else {FALSE},
                             viridis_color_map = viridis_color_map,
                             viridis_direction = viridis_direction,
                             fontsize = font.size)
        h <- out[["heatmap"]]
        h_legend <- out[["legend"]]
        list.heatmaps[[split.value]] <- h
      }
      ComplexHeatmap::ht_opt("HEATMAP_LEGEND_PADDING" = ggplot2::unit(8, "mm"))
      suppressWarnings({
        grDevices::pdf(NULL)
        ht_list <- NULL
        for (name in names(list.heatmaps)){
          ht_list <- ht_list %v% list.heatmaps[[name]]
        }
        h <- ComplexHeatmap::draw(ht_list,
                                  heatmap_legend_list = h_legend,
                                  heatmap_legend_side = if (legend.position %in% c("top", "bottom")){"bottom"} else {"right"},
                                  padding = ggplot2::unit(c(5, 5, 5, 5), "mm"))
        grDevices::dev.off()
      })
    }
    list.out[["heatmaps"]] <- list("average_scores" = h)
  }
  return(list.out)
}
```

**do_TFActivityPlot()**
```r
do_TFActivityPlot <- function(sample,
                              activities,
                              n_tfs = 25,
                              group.by = NULL,
                              split.by = NULL,
                              plot_FeaturePlots = FALSE,
                              plot_Heatmaps = TRUE,
                              plot_GeyserPlots = FALSE,
                              row_title = NULL,
                              column_title = NULL,
                              flip = FALSE,
                              cluster_cols = TRUE,
                              cluster_rows = TRUE,
                              row_names_rot = 0,
                              column_names_rot = 45,
                              cell_size = 8,
                              pt.size = 1,
                              plot_cell_borders = TRUE,
                              border.size = 2,
                              na.value = "grey75",
                              legend.position = "bottom",
                              heatmap.legend.length = 75,
                              heatmap.legend.width = 5,
                              heatmap.legend.framecolor = "black",
                              legend.width = 1,
                              legend.length = 20,
                              legend.framewidth = 0.5,
                              legend.tickwidth = 0.5,
                              legend.framecolor = "grey50",
                              legend.tickcolor = "white",
                              legend.type = "colorbar",
                              font.size = 14,
                              font.type = "sans",
                              rotate_x_axis_labels = 45,
                              enforce_symmetry = TRUE,
                              geyser_order_by_mean = TRUE,
                              geyser_scale_type = "continuous",
                              viridis_color_map = "G",
                              viridis_direction = 1,
                              min.cutoff = NULL,
                              max.cutoff = NULL){
  SCpubr:::check_suggests(function_name = "do_TFActivityPlot")
  # Check if the sample provided is a Seurat object.
  SCpubr:::check_Seurat(sample = sample)
  
  # Check logical parameters.
  logical_list <- list("plot_FeaturePlots" = plot_FeaturePlots,
                       "plot_Heatmaps" = plot_Heatmaps,
                       "plot_GeyserPlots" = plot_GeyserPlots,
                       "flip" = flip,
                       "cluster_cols" = cluster_cols,
                       "cluster_rows" = cluster_rows,
                       "plot_cell_borders" = plot_cell_borders,
                       "geyser_order_by_mean" = geyser_order_by_mean,
                       "enforce_symmetry" = enforce_symmetry)
  SCpubr:::check_type(parameters = logical_list, required_type = "logical", test_function = is.logical)
  # Check numeric parameters.
  numeric_list <- list("row_names_rot" = row_names_rot,
                       "column_names_rot" = column_names_rot,
                       "cell_size" = cell_size,
                       "heatmap.legend.length" = heatmap.legend.length,
                       "heatmap.legend.width" = heatmap.legend.width,
                       "n_tfs" = n_tfs,
                       "pt.size" = pt.size,
                       "border.size" = border.size,
                       "font.size" = font.size,
                       "legend.width" = legend.width,
                       "legend.length" = legend.length,
                       "legend.framewidth" = legend.framewidth,
                       "legend.tickwidth" = legend.tickwidth,
                       "viridis_direction" = viridis_direction,
                       "rotate_x_axis_labels" = rotate_x_axis_labels,
                       "min.cutoff" = min.cutoff,
                       "max.cutoff" = max.cutoff)
  SCpubr:::check_type(parameters = numeric_list, required_type = "numeric", test_function = is.numeric)
  # Check character parameters.
  character_list <- list("group.by" = group.by,
                         "split.by" = split.by,
                         "na.value" = na.value,
                         "legend.position" = legend.position,
                         "legend.framecolor" = legend.framecolor,
                         "font.type" = font.type,
                         "legend.tickcolor" = legend.tickcolor,
                         "legend.type" = legend.type,
                         "geyser_scale_type" = geyser_scale_type,
                         "viridis_color_map" = viridis_color_map)
  SCpubr:::check_type(parameters = character_list, required_type = "character", test_function = is.character)
  
  `%v%` <- ComplexHeatmap::`%v%`
  `%>%` <- magrittr::`%>%`
  
  SCpubr:::check_colors(legend.framecolor, parameter_name = "legend.framecolor")
  SCpubr:::check_colors(legend.tickcolor, parameter_name = "legend.tickcolor")
  SCpubr:::check_colors(heatmap.legend.framecolor, parameter_name = "heatmap.legend.framecolor")
  SCpubr:::check_colors(na.value, parameter_name = "na.value")
  
  SCpubr:::check_parameters(parameter = font.type, parameter_name = "font.type")
  SCpubr:::check_parameters(parameter = legend.type, parameter_name = "legend.type")
  SCpubr:::check_parameters(parameter = legend.position, parameter_name = "legend.position")
  SCpubr:::check_parameters(parameter = viridis_direction, parameter_name = "viridis_direction")
  SCpubr:::check_parameters(parameter = viridis_color_map, parameter_name = "viridis_color_map")
  SCpubr:::check_parameters(parameter = rotate_x_axis_labels, parameter_name = "rotate_x_axis_labels")
  
  sample[['dorothea']] <- activities %>%
    dplyr::filter(.data$statistic == 'norm_wmean') %>%
    tidyr::pivot_wider(id_cols = 'source',
                       names_from = 'condition',
                       values_from = 'score') %>%
    tibble::column_to_rownames('source') %>%
    Seurat::CreateAssayObject()
  
  Seurat::DefaultAssay(sample) <- "dorothea"
  # Scale data.
  sample <- Seurat::ScaleData(object = sample, verbose = FALSE)
  
  # Extract activities from object as a long dataframe
  suppressMessages({
    if (is.null(group.by)) {
      sample$group.by <- Seurat::Idents(sample)
    } else {
      sample$group.by <- sample@meta.data[, group.by]
    }
    df <- t(as.matrix(sample@assays$dorothea@scale.data)) %>%
      as.data.frame() %>%
      tibble::rownames_to_column(var = "cell") %>%
      dplyr::left_join(y = {sample@meta.data[, "group.by", drop = FALSE] %>%
          tibble::rownames_to_column(var = "cell")},
          by = "cell") %>%
      dplyr::select(-"cell") %>%
      tidyr::pivot_longer(cols = -"group.by",
                          names_to = "source",
                          values_to = "score") %>%
      dplyr::group_by(.data$group.by, .data$source) %>%
      dplyr::summarise(mean = mean(.data$score))
  })
  
  # Get top tfs with more variable means across clusters
  tfs <- df %>%
    dplyr::group_by(.data$source) %>%
    dplyr::summarise(std = stats::sd(.data$mean)) %>%
    dplyr::arrange(-abs(.data$std)) %>%
    dplyr::slice_head(n = n_tfs) %>%
    dplyr::pull(.data$source)
  
  # Subset long data frame to top tfs and transform to wide matrix
  top_acts_mat_long <- df %>%
    dplyr::filter(.data$source %in% tfs)
  
  top_acts_mat_wide <- top_acts_mat_long %>%
    tidyr::pivot_wider(id_cols = "group.by",
                       names_from = 'source',
                       values_from = 'mean') %>%
    tibble::column_to_rownames("group.by") %>%
    as.matrix()
  
  
  
  list.out <- list()
  
  if (isTRUE(plot_FeaturePlots)){
    list.features <- list()
    for (regulon in sort(tfs)){
      p <- do_FeaturePlot(sample = sample,
                          features = regulon,
                          assay = "dorothea",
                          reduction = "umap",
                          slot = "scale.data",
                          pt.size = pt.size,
                          order = FALSE,
                          border.size = border.size,
                          enforce_symmetry = enforce_symmetry,
                          plot_cell_borders = plot_cell_borders,
                          font.size = font.size,
                          font.type = font.type,
                          legend.title = paste0(regulon, " activity"),
                          legend.position = legend.position,
                          legend.type = legend.type,
                          legend.framecolor = legend.framecolor,
                          legend.tickcolor = legend.tickcolor,
                          legend.framewidth = legend.framewidth,
                          legend.tickwidth = legend.tickwidth,
                          legend.length = legend.length,
                          legend.width = legend.width,
                          viridis_color_map = viridis_color_map,
                          viridis_direction = viridis_direction,
                          min.cutoff = if (is.null(min.cutoff)) {NA} else {min.cutoff},
                          max.cutoff = if (is.null(max.cutoff)) {NA} else {max.cutoff})
      
      list.features[[regulon]] <- p
    }
    list.out[["feature_plots"]] <- list.features
  }
  
  if (isTRUE(plot_GeyserPlots)){
    list.geysers <- list()
    for (regulon in sort(tfs)){
      p <- do_GeyserPlot(sample = sample,
                         assay = "dorothea",
                         slot = "scale.data",
                         features = regulon,
                         group.by = group.by,
                         pt.size = pt.size,
                         border.size = border.size,
                         enforce_symmetry = enforce_symmetry,
                         scale_type = geyser_scale_type,
                         order_by_mean = geyser_order_by_mean,
                         plot_cell_borders = plot_cell_borders,
                         font.size = font.size,
                         font.type = font.type,
                         legend.position = legend.position,
                         legend.type = legend.type,
                         legend.framecolor = legend.framecolor,
                         legend.tickcolor = legend.tickcolor,
                         legend.framewidth = legend.framewidth,
                         legend.tickwidth = legend.tickwidth,
                         legend.length = legend.length,
                         legend.width = legend.width,
                         xlab = if (is.null(group.by)) {"Clusters"} else {group.by},
                         ylab = paste0(regulon, " activity"),
                         legend.title = paste0(regulon, " activity"),
                         rotate_x_axis_labels = rotate_x_axis_labels,
                         viridis_color_map = viridis_color_map,
                         viridis_direction = viridis_direction,
                         min.cutoff = min.cutoff,
                         max.cutoff = max.cutoff)
      list.geysers[[regulon]] <- p
    }
    list.out[["geyser_plots"]] <- list.geysers
  }
  
  
  if (isTRUE(plot_Heatmaps)){
    if (is.null(split.by)){
      row_title <- {
        if (!(is.null(row_title))){
          row_title
        } else {
          ""
        }}
      
      column_title <- {
        if (!(is.null(column_title))){
          column_title
        } else {
          ""
        }}
      
      if (isTRUE(flip)){
        data <- t(top_acts_mat_wide)
      } else {
        data <- top_acts_mat_wide
      }
      
      range.data <- c(min(data), max(data))
      
      if (!is.null(min.cutoff)){
        assertthat::assert_that(min.cutoff >= range.data[1],
                                msg = paste0("The value provided for min.cutoff (", min.cutoff, ") is lower than the minimum value in the enrichment matrix (", range.data[1], "). Please select another value."))
        range.data <- c(min.cutoff, range.data[2])
      }
      
      if (!is.null(max.cutoff)){
        assertthat::assert_that(max.cutoff <= range.data[2],
                                msg = paste0("The value provided for max.cutoff (", max.cutoff, ") is lower than the maximum value in the enrichment matrix (", range.data[2], "). Please select another value."))
        range.data <- c(range.data[1], max.cutoff)
        
      }
      
      out <- SCpubr:::heatmap_inner(data,
                           legend.title = "TF activity",
                           column_title = column_title,
                           row_title = row_title,
                           cluster_columns = cluster_cols,
                           cluster_rows = cluster_rows,
                           column_names_rot = column_names_rot,
                           row_names_rot = row_names_rot,
                           cell_size = cell_size,
                           na.value = na.value,
                           data_range = "both",
                           range.data = range.data,
                           legend.position = legend.position,
                           legend.length = heatmap.legend.length,
                           legend.width = heatmap.legend.width,
                           legend.framecolor = heatmap.legend.framecolor,
                           symmetrical_scale = enforce_symmetry,
                           use_viridis = if (isFALSE(enforce_symmetry)) {TRUE} else {FALSE},
                           viridis_color_map = viridis_color_map,
                           viridis_direction = viridis_direction,
                           fontsize = font.size)
      h <- out[["heatmap"]]
      h_legend <- out[["legend"]]
      ComplexHeatmap::ht_opt("HEATMAP_LEGEND_PADDING" = ggplot2::unit(8, "mm"))
      suppressWarnings({
        grDevices::pdf(NULL)
        h <- ComplexHeatmap::draw(h,
                                  heatmap_legend_list = h_legend,
                                  heatmap_legend_side = if (legend.position %in% c("top", "bottom")){"bottom"} else {"right"},
                                  padding = ggplot2::unit(c(5, 5, 5, 5), "mm"))
        grDevices::dev.off()
      })
    } else {
      split.values <- as.character(sort(unique(sample@meta.data %>% dplyr::pull(!!rlang::sym(split.by)))))
      list.heatmaps <- list()
      # Get the maximum range.
      range.data <- range.data <- c(min(top_acts_mat_wide), max(top_acts_mat_wide))
      
      if (!is.null(min.cutoff) & !is.null(max.cutoff)){
        assertthat::assert_that(min.cutoff < max.cutoff,
                                msg = paste0("The value provided for min.cutoff (", min.cutoff, ") has to be lower than the value provided to max.cutoff (", max.cutoff, "). Please select another value."))
      }
      
      if (!is.null(min.cutoff)){
        assertthat::assert_that(min.cutoff >= range.data[1],
                                msg = paste0("The value provided for min.cutoff (", min.cutoff, ") is lower than the minimum value in the enrichment matrix (", range.data[1], "). Please select another value."))
        range.data <- c(min.cutoff, range.data[2])
      }
      
      if (!is.null(max.cutoff)){
        assertthat::assert_that(max.cutoff <= range.data[2],
                                msg = paste0("The value provided for max.cutoff (", max.cutoff, ") is lower than the maximum value in the enrichment matrix (", range.data[2], "). Please select another value."))
        range.data <- c(range.data[1], max.cutoff)
        
      }
      
      for (split.value in split.values){
        suppressMessages({
          data <- sample@assays$dorothea@scale.data[tfs, ] %>%
            t() %>%
            as.data.frame() %>%
            tibble::rownames_to_column(var = "cell") %>%
            dplyr::left_join(y = {sample@meta.data[, c("group.by", split.by)] %>%
                tibble::rownames_to_column(var = "cell")},
                by = "cell") %>%
            dplyr::filter(.data[[split.by]] == split.value) %>%  # This is key.
            dplyr::select(-dplyr::all_of(c("cell", split.by))) %>%
            tidyr::pivot_longer(cols = -"group.by",
                                names_to = "source",
                                values_to = "score") %>%
            dplyr::group_by(.data$group.by, .data$source) %>%
            dplyr::summarise(mean = mean(.data$score)) %>%
            tidyr::pivot_wider(id_cols = "group.by",
                               names_from = 'source',
                               values_from = 'mean') %>%
            tibble::column_to_rownames("group.by") %>%
            as.matrix()
        })
        
        
        
        row_title <- split.value
        column_title <- ""
        
        if (isTRUE(flip)){
          data <- t(data)
        } else {
          data <- data
        }
        
        out <- SCpubr:::heatmap_inner(data,
                             legend.title = "TF Activity",
                             column_title = column_title,
                             row_title = row_title,
                             cluster_columns = cluster_cols,
                             cluster_rows = cluster_rows,
                             column_names_rot = column_names_rot,
                             row_names_rot = row_names_rot,
                             cell_size = cell_size,
                             na.value = na.value,
                             data_range = "both",
                             range.data = range.data,
                             legend.position = legend.position,
                             legend.length = heatmap.legend.length,
                             legend.width = heatmap.legend.width,
                             legend.framecolor = heatmap.legend.framecolor,
                             symmetrical_scale = enforce_symmetry,
                             use_viridis = if (isFALSE(enforce_symmetry)) {TRUE} else {FALSE},
                             viridis_color_map = viridis_color_map,
                             viridis_direction = viridis_direction,
                             fontsize = font.size)
        h <- out[["heatmap"]]
        h_legend <- out[["legend"]]
        list.heatmaps[[split.value]] <- h
      }
      ComplexHeatmap::ht_opt("HEATMAP_LEGEND_PADDING" = ggplot2::unit(8, "mm"))
      suppressWarnings({
        grDevices::pdf(NULL)
        ht_list <- NULL
        for (name in names(list.heatmaps)){
          ht_list <- ht_list %v% list.heatmaps[[name]]
        }
        h <- ComplexHeatmap::draw(ht_list,
                                  heatmap_legend_list = h_legend,
                                  heatmap_legend_side = if (legend.position %in% c("top", "bottom")){"bottom"} else {"right"},
                                  padding = ggplot2::unit(c(5, 5, 5, 5), "mm"))
        grDevices::dev.off()
      })
    }
    list.out[["heatmaps"]] <- list("average_scores" = h)
  }
  return(list.out)
}
```

Hope this helps!
Enrique

**Closed by enblacar** 2023-03-23 23:24 UTC
