### ISSUE TITLE
 "n_genes" didnt label correct number of genes in both side in "do_VolcanoPlot"

### ISSUE THREAD

**Issue by synapse73** [enblacar/SCpubr#13] opened 2022-12-15 07:18 UTC
first, thank you for this easy to use package. i really enjoy using it in my daily scRNAseq analysis.
i just encountered a little issue with the volcanoplot function.

"n_genes" works well when "order_tags_by" set to "logfc"
however, it fails to label the same number of genes in both side when "order_tags_by" was set to "both" or "p_value"
there is also a double labeling issue at certain condition
>SCpubr::do_VolcanoPlot(
    sample = daglut,
    de_genes = markers,
    n_genes = 5,
   pval_cutoff = 1e-50,
   FC_cutoff = 0.4,
   order_tags_by= "logfc"
)

![d5ce40df-a3a4-4ca1-9d57-6d4064dac840](https://user-images.githubusercontent.com/88139975/207794575-dc2addc5-9336-489c-963f-954456d9193f.png)

>SCpubr::do_VolcanoPlot(
    sample = daglut,
    de_genes = markers,
    n_genes = 5,
   pval_cutoff = 1e-50,
   FC_cutoff = 0.4,
   order_tags_by= "both"
)

![443c0185-2c92-4dc4-8594-6a337f7e3f8b](https://user-images.githubusercontent.com/88139975/207794936-86481596-c07c-4e5f-a03e-a1081a3464f1.png)

>R version 4.1.3 (2022-03-10)
Platform: x86_64-conda-linux-gnu (64-bit)
Running under: Ubuntu 20.04.1 LTS

locale:
 [1] LC_CTYPE=en_US.UTF-8       LC_NUMERIC=C              
 [3] LC_TIME=zh_CN.UTF-8        LC_COLLATE=en_US.UTF-8    
 [5] LC_MONETARY=zh_CN.UTF-8    LC_MESSAGES=en_US.UTF-8   
 [7] LC_PAPER=zh_CN.UTF-8       LC_NAME=C                 
 [9] LC_ADDRESS=C               LC_TELEPHONE=C            
[11] LC_MEASUREMENT=zh_CN.UTF-8 LC_IDENTIFICATION=C       

attached base packages:
[1] stats     graphics  grDevices utils     datasets  methods   base     

other attached packages:
[1] SCpubr_1.0.1.9000  qs_0.25.4          sp_1.5-0           SeuratObject_4.1.2
[5] Seurat_4.2.0       dplyr_1.0.10      

loaded via a namespace (and not attached):
  [1] Rtsne_0.16            colorspace_2.0-3      deldir_1.0-6         
  [4] ellipsis_0.3.2        ggridges_0.5.4        IRdisplay_1.1        
  [7] base64enc_0.1-3       spatstat.data_2.2-0   farver_2.1.1         
 [10] leiden_0.4.3          listenv_0.8.0         ggrepel_0.9.1        
 [13] fansi_1.0.3           codetools_0.2-18      splines_4.1.3        
 [16] polyclip_1.10-0       IRkernel_1.3          jsonlite_1.8.2       
 [19] Cairo_1.6-0           ica_1.0-3             cluster_2.1.4        
 [22] png_0.1-7             rgeos_0.5-9           uwot_0.1.14          
 [25] shiny_1.7.2           sctransform_0.3.5     spatstat.sparse_2.1-1
 [28] compiler_4.1.3        httr_1.4.4            assertthat_0.2.1     
 [31] Matrix_1.5-1          fastmap_1.1.0         lazyeval_0.2.2       
 [34] limma_3.50.3          cli_3.4.1             later_1.2.0          
 [37] htmltools_0.5.3       tools_4.1.3           igraph_1.3.5         
 [40] gtable_0.3.1          glue_1.6.2            RANN_2.6.1           
 [43] reshape2_1.4.4        Rcpp_1.0.8            scattermore_0.8      
 [46] vctrs_0.4.2           nlme_3.1-159          progressr_0.11.0     
 [49] lmtest_0.9-40         spatstat.random_2.2-0 stringr_1.4.1        
 [52] globals_0.16.1        mime_0.12             miniUI_0.1.1.1       
 [55] lifecycle_1.0.3       irlba_2.3.5.1         goftest_1.2-3        
 [58] future_1.28.0         MASS_7.3-58.1         zoo_1.8-11           
 [61] scales_1.2.1          spatstat.core_2.4-4   promises_1.2.0.1     
 [64] spatstat.utils_2.3-1  parallel_4.1.3        RColorBrewer_1.1-3   
 [67] reticulate_1.26       pbapply_1.5-0         gridExtra_2.3        
 [70] ggplot2_3.3.6         rpart_4.1.16          stringi_1.7.8        
 [73] repr_1.1.4            rlang_1.0.6           pkgconfig_2.0.3      
 [76] matrixStats_0.62.0    evaluate_0.17         lattice_0.20-45      
 [79] ROCR_1.0-11           purrr_0.3.5           tensor_1.5           
 [82] labeling_0.4.2        patchwork_1.1.2       htmlwidgets_1.5.4    
 [85] cowplot_1.1.1         tidyselect_1.1.2      parallelly_1.32.1    
 [88] RcppAnnoy_0.0.19      plyr_1.8.7            magrittr_2.0.3       
 [91] R6_2.5.1              generics_0.1.3        pbdZMQ_0.3-7         
 [94] DBI_1.1.3             mgcv_1.8-40           pillar_1.8.1         
 [97] fitdistrplus_1.1-8    survival_3.4-0        abind_1.4-5          
[100] tibble_3.1.8          future.apply_1.9.1    crayon_1.5.2         
[103] uuid_1.1-0            KernSmooth_2.23-20    utf8_1.2.2           
[106] RApiSerialize_0.1.2   spatstat.geom_2.4-0   plotly_4.10.0        
[109] viridis_0.6.2         grid_4.1.3            data.table_1.14.2    
[112] digest_0.6.29         xtable_1.8-4          tidyr_1.2.1          
[115] httpuv_1.6.6          RcppParallel_5.1.5    stringfish_0.15.7    
[118] munsell_0.5.0         viridisLite_0.4.1

**Comment by enblacar** [comment] 2022-12-17 13:33
Hi @synapse73,

Thanks for using my package!

I am currently unable to reproduce the bug you are facing. It will greatly help if you could send me the DE genes object you are using to reproduce the bug. Would that be an option?

If so, please send it to: scpubr@gmail.com 

Many thanks!
Enrique

**Comment by enblacar** [comment] 2023-01-08 10:58
Hi @synapse73,

Closing this as I am unable to reproduce the double tagging issue. Please feel free to reopen or still send me the DE genes object so that I can have a deeper look.

Same goes to any other user that might be facing the same issue! For the time being, the rest of problems stated are fixed, and tags can be ordered using "pvalue" and "both". The fix can be found in the last commit and will roll out in the next CRAN release (v1.1.0).

Feel free to reopen the issue with more info about the double tagging problem!

Best,
Enrique

**Closed by enblacar** 2023-01-08 10:58 UTC

**Comment by enblacar** [comment] 2023-01-11 15:17
Hi @synapse73,

SCpubr version [1.1.0](https://github.com/enblacar/SCpubr/releases/tag/v1.1.0) is already on CRAN!

Please consider updating to get all the new functionalities:

```r
install.packages("SCpubr")
```

Thanks again for using the package!
Enrique

**Comment by synapse73** [comment] 2023-01-13 03:53
hi Enrique ,
sorry i didnt reply quickly!  busy with my thesis these days.
i will definitely check SCpubr v1.1 and test my early issue.
thank you for your warm reminder!

best,
phoebe
