### ISSUE TITLE
do_DiffusionMapPlot returns empty plots

### ISSUE THREAD

**Issue by ccruizm** [enblacar/SCpubr#57] opened 2024-02-23 07:45 UTC
Hi there!

I am interested in using one of the new features, `do_DiffusionMapPlot,` but I am having issues getting the plots out. 

I am using 
```
SCpubr::do_DiffusionMapPlot(sample = sample,
                                   input_gene_list = signatures, 
                                   group.by = "cluster"
                                  )

ℹ Computing enrichment scores...

ℹ Plotting heatmaps...
```
It runs with no error but when displaying the outputs, looks like this:

![CleanShot 2024-02-23 at 08 43 54@2x](https://github.com/enblacar/SCpubr/assets/37718031/cad838be-725a-4e47-b620-e2cc0551d07a)

I just installed the latest version using devtools - SCpubr_2.0.0.9000 (CRAN package seems to be the newest version but that one does not contain the function `do_DiffusionMapPlot`)

Do you know what might be the issue?

Thanks in advance!

**Comment by enblacar** [comment] 2024-04-17 10:29
Hi @ccruizm,

I am very sorry for the late reply! I am currently writing my thesis and I did not have much time to look at the Issues.

Interesting... Have you tried updating to the latest commits (since you are using the development version anyways)? If you do, can you tell me whether the error is reproduced? 

Many thanks in advance!
Enrique

**Comment by enblacar** [comment] 2024-07-10 14:14
Hi @ccruizm,

I am closing this issue as I am unable to reproduce the bug. I would suggest upgrading to `SCpubr v2.0.2`.

FYI, for the upcoming update `v2.0.3`, I have renamed this function to `do_RankedEnrichmentPlot()` as it now accepts any dimensional reduction, and have also added a counterpart function `do_RankedExpressionPlot()` to plot individual genes instead. 

Best,
Enrique

**Closed by enblacar** 2024-07-10 14:14 UTC
